title: Zelic Page
email: thuongnh.uit@gmail.com
description: >-
  Hello there, I'm Zelic from ZelicLabs.
# baseurl: ""
url: "https://zelic91.github.io"
github_username:  zelic91

# Build settings
theme: zelic
# remote_theme: zelic91/zelic
plugins:
  - jekyll-feed
  - jekyll-remote-theme
